version: '3.8'

services:
  app:
    build: .
    ports:
      - "9292:4567"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=postgres
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d/

volumes:
  db_data: